---
title: 2021年0718日 随堂笔记2 异常机制
categories:
  - 随堂笔记
  - 2021年07月
  - 笔记
abbrlink: 25be24f9
date: 2021-07-18 14:24:43
updated: 2021-07-18 14:24:43
---

#  Java异常

## Java异常类的族谱

![image-20210718143204269](https://gitee.com/XiaoLan223/images/raw/master/Blog/Sum/20210718143204.png)

**Error程序员不关心**

## RuntimeException

运行时异常，只有在运行时，非必检查异常，编译器不回报错。

常见的有：空指针，角标越界，除零异常

数字格式化异常。

![image-20210718150432208](https://gitee.com/XiaoLan223/images/raw/master/Blog/Sum/20210718150432.png)

## 非运行时异常

继承RuntimeException,时运行时异常，其他的Exception是非运行时异常。非运行时异常编译器会检查

IOException

FileNotFoundException



## 自定义异常

一般继承Exception，不要继承RuntimException（编译器不检查）

## 异常的捕获

```java
try{
    //1
    //2
    //3
}catch(异常类型 e){

}
catch(异常类型 e){

}
```
如果catch里面的异常可以引用 抛出的异常类 则运行catch的代码块，catch的代码块运行结束以后，会这几退回整个try-catch块，不回再运行下面的catch.
所以，小的异常类型的catch块要写在上面。

**try块中的代码越少越好**

问 下面代码是否有语法错误？
```java
try{
    //1
    //2
    //3
}catch(Object e){

}
```
**没有**

### 异常的捕获过程

## finally

finally语句块一定会执行，

一般用在资源释放的，如果有多个进程引用同一个资源，而一个进程出现了异常，然后不释放掉该资源，造成其他进程等待，可能会造成死锁。

## 新版本的try-catch

```java
try{
    //1
    //2
    //3
}catch(类型1|类型2 e ){

}
```

## 返回值问题
问 下面代码的返回值是多少
```java
public int m()
{
	try{
		retrun 1;
	} finally{
		return 0;
	}
}
```
因为finally一定会执行的，所以try中的返回值会被覆盖掉，返回0

### finally语句里面不要写return语句

所以为了避免这个被覆盖的问题，finally语句块不要写return语句

## 积极处理 消极处理

使用try-catch-finally叫做积极处理

使用throws叫消极处理



## 方法重写时 的(非运行时)异常处理

- **父类方法声明异常，子类重写的方法可以不声明异常**，
- 但是如果子类也要声明异常，则该异常时只能是父类声明的**异常本事**或者父类声明的异常的**子类**。

### 子类重写父类方法时 抛出的异常不能更大，只能相等或更小

父类的方法不抛出异常，则子类重写的方法也不能抛出异常

子类重写的父类方法抛出异常A,则子类可以抛出异常A的家族,

子类方法可以抛出多个异常，但是只能是异常类A的家族类。

# 自定义异常

